export const TYPES = {
  SET_NAVIGATION_STATE: 'SET_NAVIGATION_STATE',
  SET_CURRENT_ROUTE_NAME: 'SET_CURRENT_ROUTE_NAME',
  THEME: {
    CHANGE_THEME: 'CHANGE_THEME',
    SET_DEFAULT_THEME: 'SET_DEFAULT_THEME',
  },
  PRODUCT: {
    SET_CATEGORY: 'SET_CATEGORY',
  },
};
